### ISSUE TITLE
Cannot read properties of null (reading 'useMemo') in the latest version

### ISSUE THREAD

**Issue by badasukerubin** [module-federation/vite#162] opened 2024-10-15 13:17 UTC
In version `1.0.0`, I'm able to implement mf in 2 react apps (host and remote) effectively. When building the remote in this version, I get a minimal number of outputs too. In a minified output;
```js
K=t.useMemo(function(){return Array(B).fill(null).map(function(Z,z){return{pageIndex:z,renderStatus:u.NotRenderedYet,visibility:x}})}

t=c(i)
...
var i=require$$0

...
require$$0=getAugmentedNamespace(z_mf_2_a__loadShare__react__loadShare__);
```

In version `1.1.3` on the other hand, I get the error: Cannot read properties of null (reading 'useMemo') plus PTSD from using https://github.com/originjs/vite-plugin-federation.
Sth like this in the build output.
```js
// assuming r is react 
r={current:null}

r.current.useMemo
```
```[tasklist]
### Tasks
```

**Comment by gioboa** [comment] 2024-10-15 14:00
Hi, it's a duplicate of #161 I close this one

**Closed by gioboa** 2024-10-15 14:00 UTC
