### ISSUE TITLE
v1.0.0: error in shared dependencies ending with "/"

### ISSUE THREAD

**Issue by husayt** [module-federation/vite#40] opened 2024-08-07 11:04 UTC
Some [examples](https://github.com/module-federation/core/blob/60be41eccf8cd6481e0aa7b633b095f60dfa2166/packages/nextjs-mf/README.md?plain=1#L84) show using dependencies ending with `/`, but when I try the same here I get error:

```
error when starting dev server:
Error: Missing "./" specifier in "react" package
```
 when

```
shared: {
         react:  {  },
         "react/": {  },
...
}
```

**Comment by zhangHongEn** [comment] 2024-08-10 12:40
I am not familiar with this feature, it can be added to the roadmap

**Comment by zhangHongEn** [comment] 2024-08-10 12:57
If there is a document, please send it to me. I seem to have missed the document and did not see the function of this feature.

**Comment by husayt** [comment] 2024-08-11 16:25
you can see that in official next-js MF examples

https://github.com/module-federation/core/blob/60be41eccf8cd6481e0aa7b633b095f60dfa2166/packages/nextjs-mf/README.md?plain=1#L84

**Comment by smelukov** [comment] 2024-08-19 10:36
Is there any update?

**Comment by husayt** [comment] 2024-08-19 10:37
@smelukov is it not fixed for you? I thought previous version had a fix. Can you try latest, please

**Comment by zhangHongEn** [comment] 2024-08-19 12:37
This feature was recently developed

**Comment by smelukov** [comment] 2024-08-19 12:51
> @smelukov is it not fixed for you? I thought previous version had a fix. Can you try latest, please

nope, still does'n work

**Comment by smelukov** [comment] 2024-08-21 12:51
Still actual problem

**Comment by zhangHongEn** [comment] 2024-08-22 02:16
I've been too busy recently, so I'll prioritize it this weekend.

**Comment by hi-ogawa** [comment] 2024-08-25 23:57
> vite modulePreload will bring "shared module" forward and execute it before init. I can't disable this behavior.

@zhangHongEn This looks like Rollup's `output.hoistTransitiveImports` https://rollupjs.org/configuration-options/#output-hoisttransitiveimports Can you try disabling it?

**Comment by zhangHongEn** [comment] 2024-08-26 02:13
My external is a dynamic import, but it has been modified to synchronous import. I will provide an example this afternoon


---- Replied Message ----
| From | Hiroshi ***@***.***> |
| Date | 08/26/2024 07:58 |
| To | module-federation/vite ***@***.***> |
| Cc | zhn ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [module-federation/vite] v1.0.0: error in shared dependencies ending with "/" (Issue #40) |

vite modulePreload will bring "shared module" forward and execute it before init. I can't disable this behavior.

@zhangHongEn This looks like Rollup's output.hoistTransitiveImportshttps://rollupjs.org/configuration-options/#output-hoisttransitiveimports Can you try disabling it?

**Comment by zhangHongEn** [comment] 2024-08-26 02:14
Thank you for your help. Disabling hoistTransitiveImports has not taken effect

---- Replied Message ----
| From | Hiroshi ***@***.***> |
| Date | 08/26/2024 07:58 |
| To | module-federation/vite ***@***.***> |
| Cc | zhn ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [module-federation/vite] v1.0.0: error in shared dependencies ending with "/" (Issue #40) |

vite modulePreload will bring "shared module" forward and execute it before init. I can't disable this behavior.

@zhangHongEn This looks like Rollup's output.hoistTransitiveImportshttps://rollupjs.org/configuration-options/#output-hoisttransitiveimports Can you try disabling it?

**Comment by zhangHongEn** [comment] 2024-08-26 05:03
@hi-ogawa I wrote a reproducible example
![image](https://github.com/user-attachments/assets/bde5bb91-61c0-49a5-a443-a00816bc9422)

#### rollup
![image](https://github.com/user-attachments/assets/49f675c6-7008-42bb-b3e2-4fe15ee97de7)

#### vite
![image](https://github.com/user-attachments/assets/e85ffb06-7830-41c7-9797-d65e83233542)

**Comment by hi-ogawa** [comment] 2024-08-27 02:13
@zhangHongEn Thanks for the reproduction. I'm not sure if this is technically a bug of Vite. It looks like this is a issue/limitation of `manualChunks` in general.

In your reproduction, you can mitigate the issue of `__vitePreload` creeping into a random chunk by forcing it to be inside a dedicated chunk:

```ts
        manualChunks(id) {
          ...
          // force a dedicated chunk for `__vitePreload` helper
          // since Vite/Rollup doesn't guarantee which chunk this module gets merged into.
          // https://github.com/vitejs/vite/blob/dbd6214f6fa5d35647cbd00580c76788ce894e9e/packages/vite/src/node/plugins/importAnalysisBuild.ts#L198-L208
          if (id.includes('/preload-helper.js')) {
            return "preload-helper"
          }
        }
```

**Comment by zhangHongEn** [comment] 2024-08-27 04:26
@hi-ogawa This works, I'll do it this way first, thanks for your help

**Comment by gioboa** [comment] 2024-08-29 09:33
Closed by #67

**Comment by smelukov** [comment] 2024-08-29 09:50
@zhangHongEn the last update broke our project :(

We have lerna monorepo with this structure:
- apps/host/vite.config.ts
- apps/host/...
- apps/remote1/vite.config.ts
- apps/remote1/...
- apps/remote2/vite.config.ts
- apps/remote2/...

```
failed to load config from /Users/user/project/apps/host/vite.config.ts
error when starting dev server:
Error: ENOENT: no such file or directory, open '/Users/user/project/apps/host/node_modules/__mf__virtual/empty.js'
    at Object.openSync (node:fs:600:3)
    at Object.writeFileSync (node:fs:2221:35)
    at Object.<anonymous> (/Users/user/project/node_modules/@module-federation/vite/lib/index.cjs:317:4)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by smelukov** [comment] 2024-08-29 09:51
@gioboa can we reopen the issue?

**Comment by zhangHongEn** [comment] 2024-08-29 09:53
> @zhangHongEn the last update broke our project :(
> 
> We have lerna monorepo with this structure:
> 
> * apps/host/vite.config.ts
> * apps/host/...
> * apps/remote1/vite.config.ts
> * apps/remote1/...
> * apps/remote2/vite.config.ts
> * apps/remote2/...
> 
> ```
> failed to load config from /Users/user/project/apps/host/vite.config.ts
> error when starting dev server:
> Error: ENOENT: no such file or directory, open '/Users/user/project/apps/host/node_modules/__mf__virtual/empty.js'
>     at Object.openSync (node:fs:600:3)
>     at Object.writeFileSync (node:fs:2221:35)
>     at Object.<anonymous> (/Users/user/project/node_modules/@module-federation/vite/lib/index.cjs:317:4)
>     at Module._compile (node:internal/modules/cjs/loader:1218:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
>     at Module.load (node:internal/modules/cjs/loader:1081:32)
>     at Module._load (node:internal/modules/cjs/loader:922:12)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
>     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
> ```
Ok maybe it's incompatible with lerna monorepo, I'll fix it

**Comment by smelukov** [comment] 2024-08-29 09:55
@zhangHongEn thanks!
We use lerna with `useNx: true`

**Comment by husayt** [comment] 2024-08-29 10:34
@smelukov @zhangHongEn @gioboa as we are moving forward it is important to make sure while fixing issues and adding new features we don't introduce regressions, as this is causing a lot of pain to end users. That was one of the reasons I tried to add examples with main features to make sure we can run them to see visually if anything affected. Moving forward will be great to add more examples like that, which could be our first line of defence, but also might be useful to think about integration and unit tests which could help to prevent as well. We might open a new ticket here to discuss ideas and suggestions for this.

**Comment by zhangHongEn** [comment] 2024-08-29 11:06
Yes, currently we rely entirely on examples to ensure quality, which is very important now.

**Comment by zhangHongEn** [comment] 2024-08-29 11:07
@smelukov I may know where the path setting is wrong, but I tried to reproduce it with learn and failed. Can you provide more information? Can you provide an example?

**Comment by smelukov** [comment] 2024-08-29 11:20
@zhangHongEn here is an example https://github.com/smelukov/mf-vite-nx-bug
```sh
npm i
npm start
```

**Comment by zhangHongEn** [comment] 2024-08-31 07:34
@smelukov Fixed, nx demo is running normally

**Comment by gioboa** [comment] 2024-08-31 08:48
Thanks @zhangHongEn

**Closed** 2024-08-31 08:48 UTC

**Comment by smelukov** [comment] 2024-09-03 14:24
@zhangHongEn @gioboa our project is still broken :(
Another errors at this time:

```
✘ [ERROR] No loader is configured for ".ttf" files: ../../node_modules/out-uikit-library/lib/styles/fonts/Inter-Bold.ttf

    ../../node_modules/out-uikit-library/lib/styles/fonts.css:34:11:
      34 │   src: url('fonts/Inter-Bold.ttf');
         ╵            ~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".ttf" files: ../../node_modules/out-uikit-library/lib/styles/fonts/PTMono-Regular.ttf

    ../../node_modules/out-uikit-library/lib/styles/fonts.css:49:11:
      49 │   src: url('fonts/PTMono-Regular.ttf');
         ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~

4:33:52 PM [vite] error while updating dependencies:
Error: Build failed with 11 errors:
../../node_modules/out-uikit-library/lib/styles/fonts.css:4:11: ERROR: No loader is configured for ".ttf" files: ../../node_modules/out-uikit-library/lib/styles/fonts/Inter-Thin.ttf
../../node_modules/out-uikit-library/lib/styles/fonts.css:9:11: ERROR: No loader is configured for ".ttf" files: ../../node_modules/out-uikit-library/lib/styles/fonts/Inter-ExtraLight.ttf
../../node_modules/out-uikit-library/lib/styles/fonts.css:14:11: ERROR: No loader is configured for ".ttf" files: ../../node_modules/out-uikit-library/lib/styles/fonts/Inter-Light.ttf
../../node_modules/out-uikit-library/lib/styles/fonts.css:19:11: ERROR: No loader is configured for ".ttf" files: ../../node_modules/out-uikit-library/lib/styles/fonts/Inter-Regular.ttf
../../node_modules/out-uikit-library/lib/styles/fonts.css:24:11: ERROR: No loader is configured for ".ttf" files: ../../node_modules/out-uikit-library/lib/styles/fonts/Inter-Medium.ttf
...
    at failureErrorWithLog (/path/to/project/node_modules/esbuild/lib/main.js:1472:15)
    at /path/to/project/node_modules/esbuild/lib/main.js:945:25
    at /path/to/project/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

We do not have this error if we use the module federation plugin for webpack. Moreover, we use cssinjs and our project does not import any CSS files.
In this case, we see how something imports a CSS file and this CSS file imports some fonts.
This is unexpected behaviour

**Comment by smelukov** [comment] 2024-09-03 14:30
@smelukov This error is about a feature that was implemented for this issue. Should I create a new issue anyway?

**Comment by gioboa** [comment] 2024-09-03 14:57
If I understand the problem correctly, now you have
`No loader is configured for ".ttf" files: ../../node_modules/out-uikit-library/lib/styles/fonts/Inter-Bold.ttf` so should be a different one.
