### ISSUE TITLE
Multiple runtime loaded

### ISSUE THREAD

**Issue by smelukov** [module-federation/vite#42] opened 2024-08-09 11:57 UTC
Just use one https://github.com/module-federation/vite/tree/new-config/examples/vite as a host and one another as a remote. In this case, the module federation runtime chunk is loaded multiple times. Sometimes this leads to a race condition and error with the message "Call init first". If we have 10 vite remotes, then 10 runtime chunks will be loaded. 
We need to load and use only one runtime, especially if we use different bundlers (e.g. webpack host, 2 vite remotes, 3 webpack remotes).

@zhangHongEn

![image](https://github.com/user-attachments/assets/8126e9ce-93ef-4ed4-b93f-7fd91f78b561)

**Comment by gioboa** [comment] 2024-08-09 14:06
Thanks @smelukov  for your feedback. Are you using the latest alpha version?

**Comment by smelukov** [comment] 2024-08-09 14:07
> Are you using the latest alpha version?

yes

**Comment by zhangHongEn** [comment] 2024-08-09 16:00
#39 Let me solve this more serious problem first, and then look at this。

Does the "Call init first" error appear randomly after multiple refreshes, or does it appear once every time you start dev for the first time and disappear after a refresh?

**Comment by smelukov** [comment] 2024-08-10 06:02
@zhangHongEn It seems like "Call init first" appears on the first refresh after the build has started

**Comment by zhangHongEn** [comment] 2024-08-10 06:27
OK, the dynamic module has a minor flaw when building in vite dev. You need to initiate a request first, that is, refresh the page once and it will be normal.

**Comment by zhangHongEn** [comment] 2024-08-10 06:28
> Just use one https://github.com/module-federation/vite/tree/new-config/examples/vite as a host and one another as a remote. In this case, the module federation runtime chunk is loaded multiple times. Sometimes this leads to a race condition and error with the message "Call init first". If we have 10 vite remotes, then 10 runtime chunks will be loaded. We need to load and use only one runtime, especially if we use different bundlers (e.g. webpack host, 2 vite remotes, 3 webpack remotes).
> 
> @zhangHongEn
> 
> ![image](https://private-user-images.githubusercontent.com/6654581/356581018-8126e9ce-93ef-4ed4-b93f-7fd91f78b561.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzE1MzUsIm5iZiI6MTcyMzI3MTIzNSwicGF0aCI6Ii82NjU0NTgxLzM1NjU4MTAxOC04MTI2ZTljZS05M2VmLTRlZDQtYjkzZi03ZmQ5MWY3OGI1NjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMDYyNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjBiZGJjMWI5ZmMzZWJmNGI0ZTYzZmM0ZmFmNTRiNzg1YTRlOGQxZTg3MGUyYmMzZmQyMDhkZDVmOTNmMDg5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3R9FQkBfOLAxUARUc1TYj2c06Olj1o9tkwjZsvMEw-c)

If these two @module-federation_runtime.js are on different ports, it is normal

**Comment by smelukov** [comment] 2024-08-10 06:30
Yes, these are on different ports, but the mf-runtime should be a singleton, so multiple runtimes break this behaviour. Isn't it?

**Comment by zhangHongEn** [comment] 2024-08-10 06:40
@smelukov  The only object that must be a singleton is the "shared" object. The host is the only one that will create the "shared" object, and the other remotes will receive it when they enter the init parameter.

**Comment by zhangHongEn** [comment] 2024-08-10 06:45
If mf-runtime is a single instance, all remote modules' mf-runtime will be forced to use the host, which may cause version inconsistency and missing APIs (such as runtime APIs). Therefore, mf-runtime is usually multi-instance.

**Comment by husayt** [comment] 2024-08-11 00:18
I get this with latest now

**Comment by zhangHongEn** [comment] 2024-08-11 13:07
@husayt I'm not sure if the new pre-bunding shared solution is not compatible with Windows, because I can't reproduce it. Let me check it out.

**Comment by husayt** [comment] 2024-08-11 13:09
> @husayt I'm not sure if the new pre-bunding shared solution is not compatible with Windows, because I can't reproduce it. Let me check it out.

let me know if you need any more details from me. but latest cut breaks both host and remote for me. i have spend whole night trying to make it work

**Comment by zhangHongEn** [comment] 2024-08-11 14:41
@husayt Windows issues fixed

**Comment by husayt** [comment] 2024-08-11 16:29
@zhangHongEn it indeed works finally. @gioboa can we get it approved please. 

Also, while you are on it I raised a PR with updated examples and dependencies
https://github.com/module-federation/vite/pull/50

@zhangHongEn one key problem there is that seems images are not properly imported. I added an example of SASS with image background. When you run standalone remote it shows dark background, but when run from inside host it doesn't show image

**Comment by gioboa** [comment] 2024-08-11 19:17
Closed by #48

**Closed** 2024-08-11 19:17 UTC
